/**
 * Sign in plumbing, run with `npm run test:auth`. Offline, no network, no
 * account: every key below is an obviously fake byte string.
 *
 * **What this is protecting.** Between the provider's answer and
 * `deriveFromSignature` there are about forty lines that normalise a signature
 * into the 65 bytes an Ethereum wallet would have produced. Every one of those
 * lines can be wrong in a way that still yields a well formed signature, and a
 * well formed wrong signature derives a perfectly valid, perfectly empty
 * shielded account. Nothing throws. The user sees a balance of zero.
 *
 * So the expectations below are **known answers generated by viem**, at 2.55.8,
 * from `app/`, which is the library the self custody dapp actually signs with.
 * That is the point: the assertion is not that this code is self consistent, it
 * is that this code produces the same bytes an injected wallet would for the
 * same key and the same message. That equality is what makes the two clients one
 * shielded account space, and it is the thing an export depends on.
 *
 * The one property these vectors cannot reach is whether **the provider**
 * returns those bytes, because signing happens in somebody else's TEE and no
 * provider has put RFC 6979 on the public record. `scripts/privyprobe.mts`
 * answers that against a real account, and it has to be run before anybody holds
 * a balance.
 */
import { secp256k1 } from "@noble/curves/secp256k1";
import { keccak_256 } from "@noble/hashes/sha3";
import { hexToBytes } from "@noble/hashes/utils";
import { SHIELDED_SIGN_MESSAGE } from "../src/features/keys";
import { __unlock } from "../src/features/auth/lib/unlock";
import { isUnlockError } from "../src/features/auth/lib/errors";

const { eip191, normalise, verify, address } = __unlock;

let failures = 0;

function check(name: string, ok: boolean, detail?: string) {
  if (ok) {
    console.log(`  ok    ${name}`);
  } else {
    failures++;
    console.log(`  FAIL  ${name}${detail ? `\n          ${detail}` : ""}`);
  }
}

/**
 * `actual` is a thunk rather than a value so that a check which throws is
 * reported as one failed line instead of ending the run.
 *
 * Found by mutation: changing the recovery byte arithmetic made `assemble`
 * refuse its own known answers, the exception escaped, and the script died at
 * the first vector with a stack trace and no summary. The exit code was still
 * right, so CI would have caught it, and the person reading the output would
 * have learned nothing about how much else was broken.
 */
function eq(name: string, actual: () => unknown, expected: unknown) {
  let a: string;
  try {
    a = String(actual());
  } catch (err) {
    check(name, false, `threw: ${(err as Error)?.message}`);
    return;
  }
  const e = String(expected);
  check(name, a === e, a === e ? undefined : `expected ${e}\n          actual   ${a}`);
}

function throws(name: string, fn: () => unknown) {
  try {
    fn();
    check(name, false, "expected it to throw, it returned");
  } catch (err) {
    // An UnlockError is a refusal this code wrote. Anything else is a crash that
    // happened to land in the right place, which is not the same thing.
    check(name, isUnlockError(err), `threw ${(err as Error)?.name}, wanted UnlockError`);
  }
}

/**
 * Refused, **and refused for the stated reason**.
 *
 * `throws` alone was not enough and a mutation proved it. Loosening the length
 * check in `normalise` from `!== 130` to `> 130` left every short-signature case
 * still passing: a 64 byte input sailed past the length gate, `v` parsed to NaN,
 * and the function threw an `UnlockError` from the next check down. The test was
 * green for a reason that had nothing to do with what it claimed to pin.
 *
 * So the cases that exist to pin one specific refusal name it. The `reason` is
 * this project's own text and never a provider's, which is what makes it safe to
 * match on.
 */
function throwsBecause(name: string, fn: () => unknown, pattern: RegExp) {
  try {
    fn();
    check(name, false, "expected it to throw, it returned");
  } catch (err) {
    if (!isUnlockError(err)) {
      check(name, false, `threw ${(err as Error)?.name}, wanted UnlockError`);
      return;
    }
    check(name, pattern.test(err.reason),
      `refused, but for the wrong reason: ${err.reason}`);
  }
}

/**
 * Generated on 2026-08-08 by `privateKeyToAccount(pk).signMessage({ message })`
 * at viem 2.55.8, signing `SHIELDED_SIGN_MESSAGE`.
 *
 * `r`, `s` and `v` are that signature taken apart, with `v` written as a bare
 * recovery id of 00 or 01 rather than Ethereum's 27 or 28. Joined in that form
 * and normalised, they have to give `sig` back.
 *
 * **The fields are kept even though the current provider returns `sig` whole.**
 * A provider that writes the recovery byte the other way is a different shielded
 * account for everybody, and these vectors are what turns that into a failing
 * test rather than a silent migration.
 */
const VECTORS = [
  {
    address: "0x19E7E376E7C213B7E7e7e46cc70A5dD086DAff2A",
    r: "90fa198d0ba11bd27537289b280e7825a996cadc2eb20078948f9b8f3b399c08",
    s: "2c1c7d3873b75a3d3dd455c53ddd21610a153dedc8d53a75bffa9b22a36e2cda",
    v: "01",
    sig:
      "0x90fa198d0ba11bd27537289b280e7825a996cadc2eb20078948f9b8f3b399c08" +
      "2c1c7d3873b75a3d3dd455c53ddd21610a153dedc8d53a75bffa9b22a36e2cda1c",
  },
  {
    address: "0x1E4e0351424123871305C2Ce3Bc4a955B183BfF5",
    r: "690495c87204916dce9189ad36b9c90b6d90315e683cdf01877673c66edfb34b",
    s: "4a634b60e17be6bafa0500dd3e805eef0d3d2aa5b34a96d8c2d5145282431bee",
    v: "00",
    sig:
      "0x690495c87204916dce9189ad36b9c90b6d90315e683cdf01877673c66edfb34b" +
      "4a634b60e17be6bafa0500dd3e805eef0d3d2aa5b34a96d8c2d5145282431bee1b",
  },
];

const MESSAGE = eip191(SHIELDED_SIGN_MESSAGE);

console.log("\nThe bytes an Ethereum wallet signs");
{
  // The length in the prefix counts bytes, not characters. Getting this wrong
  // produces a signature no other wallet agrees with, silently.
  const body = new TextEncoder().encode(SHIELDED_SIGN_MESSAGE);
  const expected = `\x19Ethereum Signed Message:\n${body.length}`;
  eq("prefix names the byte length",
    () => new TextDecoder().decode(MESSAGE.subarray(0, expected.length)), expected);
  eq("message follows the prefix unchanged",
    () => new TextDecoder().decode(MESSAGE.subarray(expected.length)), SHIELDED_SIGN_MESSAGE);

  // A non-ascii message is where a character count and a byte count diverge.
  // Cowl's message is ascii today, and this is the check that notices if it
  // stops being, in a codebase where that string is the seed of every account.
  eq("a two byte character is counted as two",
    () => new TextDecoder().decode(eip191("é")), "\x19Ethereum Signed Message:\n2é");
}

console.log("\nNormalisation, against known answers from viem");
for (const [i, v] of VECTORS.entries()) {
  eq(`vector ${i} · a bare recovery id becomes viem's signature`,
    () => normalise(v.r + v.s + v.v), v.sig);

  // Privy returns the Ethereum form already, so this is the identity case. It
  // is asserted rather than assumed because a normaliser that quietly altered
  // an already correct signature is the same bug as one that failed to fix a
  // wrong one, and neither throws.
  eq(`vector ${i} · an already Ethereum signature is left alone`,
    () => normalise(v.sig), v.sig);

  eq(`vector ${i} · a 0x prefix is tolerated`,
    () => normalise("0x" + v.r + v.s + v.v), v.sig);

  eq(`vector ${i} · upper case hex is accepted and lowered`,
    () => normalise((v.r + v.s + v.v).toUpperCase()), v.sig);

  eq(`vector ${i} · verifies against its own address`,
    () => { verify(v.sig, MESSAGE, v.address); return "accepted"; }, "accepted");

  eq(`vector ${i} · recovers the address viem reported`,
    () => address(secp256k1.Signature.fromCompact(hexToBytes(v.sig.slice(2, 130)))
      .addRecoveryBit(Number.parseInt(v.sig.slice(130), 16) - 27)
      .recoverPublicKey(keccak_256(MESSAGE)).toRawBytes(false)),
    v.address.toLowerCase());
}

console.log("\nRefusals · every one of these is a silently empty account otherwise");
{
  const v = VECTORS[0]!;

  // The wrong recovery byte recovers a different, entirely valid public key.
  // Nothing downstream can tell that account from the right one.
  const flippedV = "0x" + v.r + v.s + "1b";
  throws("a flipped recovery byte is refused", () => verify(flippedV, MESSAGE, v.address));

  throws("a signature from another wallet is refused", () =>
    verify(VECTORS[1]!.sig, MESSAGE, v.address));

  throws("a signature over a different message is refused", () =>
    verify(v.sig, eip191("something else entirely"), v.address));

  // Both halves of the curve are valid ECDSA and both recover this address, so
  // only the explicit check catches it. If the provider ever returned the high
  // form, exporting the key into an injected wallet would open a different
  // account.
  const high = (() => {
    const n = secp256k1.CURVE.n;
    const s = n - BigInt("0x" + v.s);
    const otherV = v.sig.slice(130) === "1c" ? "1b" : "1c";
    return "0x" + v.r + s.toString(16).padStart(64, "0") + otherV;
  })();
  eq("the high s form still recovers the same address, which is why it needs its own check",
    () => address(secp256k1.Signature.fromCompact(hexToBytes(high.slice(2, 130)))
      .addRecoveryBit(Number.parseInt(high.slice(130), 16) - 27)
      .recoverPublicKey(keccak_256(MESSAGE)).toRawBytes(false)),
    v.address.toLowerCase());
  throws("a high s signature is refused", () => verify(high, MESSAGE, v.address));

  throws("a recovery value that is neither 0, 1, 27 nor 28 is refused", () =>
    normalise(v.r + v.s + "07"));
  throws("a non hex signature is refused", () => normalise("zz".repeat(65)));

  /*
    **Length is the check that replaced a per field one, and the swap is worth
    reading.** The previous provider returned `r` and `s` separately with leading
    zeroes stripped, so the danger was a 31 byte field being joined unpadded:
    every offset after it shifted and the account changed. A provider that hands
    over one joined string cannot produce that, but it can produce a truncated or
    over long one, and the failure is identical · a signature of the wrong length
    read as though it were the right one. Refusing on length is the same
    protection at the new seam rather than one fewer check.
  */
  throwsBecause("a signature one byte short is refused for its length",
    () => normalise(v.r + v.s), /65 bytes/);
  throwsBecause("a signature one byte long is refused for its length",
    () => normalise(v.r + v.s + v.v + "00"), /65 bytes/);
  throwsBecause("an empty signature is refused for its length",
    () => normalise(""), /65 bytes/);
}

console.log(
  failures === 0
    ? "\nAll checks passed. This client reassembles the same signature an injected wallet would.\n"
    : `\n${failures} check(s) failed.\n`,
);
process.exit(failures === 0 ? 0 : 1);
