/**
 * Sign in plumbing, run with `npm run test:auth`. Offline, no network, no
 * account: every key below is an obviously fake byte string.
 *
 * **What this is protecting.** Between Turnkey's answer and
 * `deriveFromSignature` there are about forty lines that reassemble three hex
 * fields into the 65 bytes an Ethereum wallet would have produced. Every one of
 * those lines can be wrong in a way that still yields a well formed signature,
 * and a well formed wrong signature derives a perfectly valid, perfectly empty
 * shielded account. Nothing throws. The user sees a balance of zero.
 *
 * So the expectations below are **known answers generated by viem**, at 2.55.8,
 * from `app/`, which is the library the self custody dapp actually signs with.
 * That is the point: the assertion is not that this code is self consistent, it
 * is that this code produces the same bytes an injected wallet would for the
 * same key and the same message. That equality is what makes the two clients one
 * shielded account space, and it is the thing an export depends on.
 *
 * The one property these vectors cannot reach is whether **Turnkey** returns
 * those bytes, because Turnkey is not RFC 6979 on the public record and its
 * enclave has an entropy source. `scripts/turnkeyprobe.mts` answers that against
 * a real account, and it has to be run before anybody holds a balance.
 */
import { p256 } from "@noble/curves/p256";
import { secp256k1 } from "@noble/curves/secp256k1";
import { keccak_256 } from "@noble/hashes/sha3";
import { bytesToHex, hexToBytes } from "@noble/hashes/utils";
import { SHIELDED_SIGN_MESSAGE } from "../src/features/keys";
import { __unlock } from "../src/features/auth/lib/unlock";
import { isUnlockError } from "../src/features/auth/lib/errors";
import { __encoding } from "../src/features/auth/lib/session-key";

const { eip191, assemble, verify, address } = __unlock;
const { compressP256, ieee1363ToDer, base64url, toHex } = __encoding;

let failures = 0;

function check(name: string, ok: boolean, detail?: string) {
  if (ok) {
    console.log(`  ok    ${name}`);
  } else {
    failures++;
    console.log(`  FAIL  ${name}${detail ? `\n          ${detail}` : ""}`);
  }
}

/**
 * `actual` is a thunk rather than a value so that a check which throws is
 * reported as one failed line instead of ending the run.
 *
 * Found by mutation: changing the recovery byte arithmetic made `assemble`
 * refuse its own known answers, the exception escaped, and the script died at
 * the first vector with a stack trace and no summary. The exit code was still
 * right, so CI would have caught it, and the person reading the output would
 * have learned nothing about how much else was broken.
 */
function eq(name: string, actual: () => unknown, expected: unknown) {
  let a: string;
  try {
    a = String(actual());
  } catch (err) {
    check(name, false, `threw: ${(err as Error)?.message}`);
    return;
  }
  const e = String(expected);
  check(name, a === e, a === e ? undefined : `expected ${e}\n          actual   ${a}`);
}

function throws(name: string, fn: () => unknown) {
  try {
    fn();
    check(name, false, "expected it to throw, it returned");
  } catch (err) {
    // An UnlockError is a refusal this code wrote. Anything else is a crash that
    // happened to land in the right place, which is not the same thing.
    check(name, isUnlockError(err), `threw ${(err as Error)?.name}, wanted UnlockError`);
  }
}

/** For the encoding helpers, which are below the layer that has an error type. */
function throwsAnything(name: string, fn: () => unknown) {
  try {
    fn();
    check(name, false, "expected it to throw, it returned");
  } catch {
    check(name, true);
  }
}

/**
 * Generated on 2026-08-08 by `privateKeyToAccount(pk).signMessage({ message })`
 * at viem 2.55.8, signing `SHIELDED_SIGN_MESSAGE`.
 *
 * `r`, `s` and `v` are that signature taken apart into the three fields Turnkey
 * returns, with `v` written the way Turnkey writes it, as a recovery id of 00 or
 * 01 rather than Ethereum's 27 or 28. Reassembling them has to give `sig` back.
 */
const VECTORS = [
  {
    address: "0x19E7E376E7C213B7E7e7e46cc70A5dD086DAff2A",
    r: "90fa198d0ba11bd27537289b280e7825a996cadc2eb20078948f9b8f3b399c08",
    s: "2c1c7d3873b75a3d3dd455c53ddd21610a153dedc8d53a75bffa9b22a36e2cda",
    v: "01",
    sig:
      "0x90fa198d0ba11bd27537289b280e7825a996cadc2eb20078948f9b8f3b399c08" +
      "2c1c7d3873b75a3d3dd455c53ddd21610a153dedc8d53a75bffa9b22a36e2cda1c",
  },
  {
    address: "0x1E4e0351424123871305C2Ce3Bc4a955B183BfF5",
    r: "690495c87204916dce9189ad36b9c90b6d90315e683cdf01877673c66edfb34b",
    s: "4a634b60e17be6bafa0500dd3e805eef0d3d2aa5b34a96d8c2d5145282431bee",
    v: "00",
    sig:
      "0x690495c87204916dce9189ad36b9c90b6d90315e683cdf01877673c66edfb34b" +
      "4a634b60e17be6bafa0500dd3e805eef0d3d2aa5b34a96d8c2d5145282431bee1b",
  },
];

const MESSAGE = eip191(SHIELDED_SIGN_MESSAGE);

console.log("\nThe bytes an Ethereum wallet signs");
{
  // The length in the prefix counts bytes, not characters. Getting this wrong
  // produces a signature no other wallet agrees with, silently.
  const body = new TextEncoder().encode(SHIELDED_SIGN_MESSAGE);
  const expected = `\x19Ethereum Signed Message:\n${body.length}`;
  eq("prefix names the byte length",
    () => new TextDecoder().decode(MESSAGE.subarray(0, expected.length)), expected);
  eq("message follows the prefix unchanged",
    () => new TextDecoder().decode(MESSAGE.subarray(expected.length)), SHIELDED_SIGN_MESSAGE);

  // A non-ascii message is where a character count and a byte count diverge.
  // Cowl's message is ascii today, and this is the check that notices if it
  // stops being, in a codebase where that string is the seed of every account.
  eq("a two byte character is counted as two",
    () => new TextDecoder().decode(eip191("é")), "\x19Ethereum Signed Message:\n2é");
}

console.log("\nReassembly, against known answers from viem");
for (const [i, v] of VECTORS.entries()) {
  eq(`vector ${i} · r, s and a recovery id rebuild viem's signature`,
    () => assemble({ r: v.r, s: v.s, v: v.v }), v.sig);

  // Turnkey documents 00 and 01. Accepting 1b and 1c too means a change of
  // convention on their side surfaces here rather than as a different key.
  eq(`vector ${i} · an already Ethereum recovery byte is left alone`,
    () => assemble({ r: v.r, s: v.s, v: v.v === "00" ? "1b" : "1c" }), v.sig);

  eq(`vector ${i} · 0x prefixes on the fields are tolerated`,
    () => assemble({ r: "0x" + v.r, s: "0x" + v.s, v: "0x" + v.v }), v.sig);

  eq(`vector ${i} · verifies against its own address`,
    () => { verify(v.sig, MESSAGE, v.address); return "accepted"; }, "accepted");

  eq(`vector ${i} · recovers the address viem reported`,
    () => address(secp256k1.Signature.fromCompact(hexToBytes(v.sig.slice(2, 130)))
      .addRecoveryBit(Number.parseInt(v.sig.slice(130), 16) - 27)
      .recoverPublicKey(keccak_256(MESSAGE)).toRawBytes(false)),
    v.address.toLowerCase());
}

console.log("\nRefusals · every one of these is a silently empty account otherwise");
{
  const v = VECTORS[0]!;

  // The wrong recovery byte recovers a different, entirely valid public key.
  // Nothing downstream can tell that account from the right one.
  const flippedV = "0x" + v.r + v.s + "1b";
  throws("a flipped recovery byte is refused", () => verify(flippedV, MESSAGE, v.address));

  throws("a signature from another wallet is refused", () =>
    verify(VECTORS[1]!.sig, MESSAGE, v.address));

  throws("a signature over a different message is refused", () =>
    verify(v.sig, eip191("something else entirely"), v.address));

  // Both halves of the curve are valid ECDSA and both recover this address, so
  // only the explicit check catches it. If Turnkey ever returned the high form,
  // exporting the key into an injected wallet would open a different account.
  const high = (() => {
    const n = secp256k1.CURVE.n;
    const s = n - BigInt("0x" + v.s);
    const otherV = v.sig.slice(130) === "1c" ? "1b" : "1c";
    return "0x" + v.r + s.toString(16).padStart(64, "0") + otherV;
  })();
  eq("the high s form still recovers the same address, which is why it needs its own check",
    () => address(secp256k1.Signature.fromCompact(hexToBytes(high.slice(2, 130)))
      .addRecoveryBit(Number.parseInt(high.slice(130), 16) - 27)
      .recoverPublicKey(keccak_256(MESSAGE)).toRawBytes(false)),
    v.address.toLowerCase());
  throws("a high s signature is refused", () => verify(high, MESSAGE, v.address));

  throws("a recovery value that is neither 0, 1, 27 nor 28 is refused", () =>
    assemble({ r: v.r, s: v.s, v: "07" }));
  throws("a non hex field is refused", () => assemble({ r: "zz", s: v.s, v: v.v }));
  throws("an oversized field is refused", () => assemble({ r: "ff" + v.r, s: v.s, v: v.v }));

  // Turnkey strips leading zeroes on these fields. Left unpadded the signature
  // is 64 bytes, every offset after it shifts, and the account changes.
  eq("a short field is padded back to 32 bytes",
    () => assemble({ r: "abc", s: "def", v: "00" }),
    "0x" + "abc".padStart(64, "0") + "def".padStart(64, "0") + "1b");
}

console.log("\nStamp encoding · what Turnkey checks every request against");
{
  // P-256 point compression, checked against noble rather than against itself.
  for (let i = 0; i < 4; i++) {
    const priv = p256.utils.randomPrivateKey();
    const uncompressed = p256.getPublicKey(priv, false);
    eq(`compressed point ${i} matches noble`,
      () => compressP256(uncompressed), bytesToHex(p256.getPublicKey(priv, true)));
  }
  throwsAnything("an uncompressed point is required", () => compressP256(new Uint8Array(33)));

  // WebCrypto returns r || s. Turnkey wants DER. noble is the reference.
  for (let i = 0; i < 6; i++) {
    const priv = p256.utils.randomPrivateKey();
    const sig = p256.sign(keccak_256(new Uint8Array([i])), priv);
    const ieee = new Uint8Array(64);
    ieee.set(hexToBytes(sig.r.toString(16).padStart(64, "0")), 0);
    ieee.set(hexToBytes(sig.s.toString(16).padStart(64, "0")), 32);
    eq(`der signature ${i} matches noble`, () => toHex(ieee1363ToDer(ieee)), sig.toDERHex());
  }

  // The high bit case, which is the one a hand rolled DER encoder gets wrong:
  // a leading byte of 0x80 or more has to be padded or it reads as negative.
  const highBit = new Uint8Array(64).fill(0xff);
  eq("a field with the high bit set is padded", () => toHex(ieee1363ToDer(highBit)),
    "3046" + "0221" + "00" + "ff".repeat(32) + "0221" + "00" + "ff".repeat(32));

  // And the other end: leading zeroes come off rather than being encoded.
  const leadingZero = new Uint8Array(64);
  leadingZero[31] = 1;
  leadingZero[63] = 2;
  eq("leading zeroes are trimmed", () => toHex(ieee1363ToDer(leadingZero)),
    "3006" + "020101" + "020102");

  eq("base64url matches node, ascii", () => base64url("hello?/+world"),
    Buffer.from("hello?/+world", "utf8").toString("base64url"));
  // btoa alone throws on this. The stamp is JSON from a server's fields.
  eq("base64url matches node, non ascii", () => base64url('{"n":"café · 日本"}'),
    Buffer.from('{"n":"café · 日本"}', "utf8").toString("base64url"));
}

console.log(
  failures === 0
    ? "\nAll checks passed. This client reassembles the same signature an injected wallet would.\n"
    : `\n${failures} check(s) failed.\n`,
);
process.exit(failures === 0 ? 0 : 1);
