/**
 * Key derivation parity, run with `npm run test:keys`. Offline, no network, no
 * secret involved: every signature below is a fixed, obviously fake byte string.
 *
 * **What this is actually protecting.** app-v2 and the self custody dapp are one
 * shielded account space by design, so the same wallet has to produce the same
 * `mpk` and the same `zcowl1…` in both. If this file ever drifts from
 * `app/lib/shielded/keys.ts`, nothing throws and nothing looks broken. A user
 * signs in, the app derives a different account, and their balance reads zero
 * while the notes sit in the pool addressed to keys this client will never
 * derive again. That failure is silent, it looks exactly like theft, and it is
 * unrecoverable, because a note belongs to whoever holds the `sk` behind its
 * `mpk` and nothing on chain records that it moved.
 *
 * So the expectations below are **known answers generated from the shipped
 * dapp**, not from this implementation. Regenerating them from app-v2 would make
 * the check agree with whatever it currently does, which is the one thing it
 * must not do. To regenerate honestly, run the derivation in `app/` and paste.
 */
import { deriveFromSignature, SHIELDED_SIGN_MESSAGE } from "../src/features/keys";
import {
  decodePaymentAddress,
  encodePaymentAddress,
  isPaymentAddress,
} from "../src/lib/payment-address";
import { FR } from "../src/lib/field";

let failures = 0;

function check(name: string, ok: boolean, detail?: string) {
  if (ok) {
    console.log(`  ok    ${name}`);
  } else {
    failures++;
    console.log(`  FAIL  ${name}${detail ? `\n          ${detail}` : ""}`);
  }
}

function eq(name: string, actual: unknown, expected: unknown) {
  const a = typeof actual === "bigint" ? actual.toString() : String(actual);
  const e = typeof expected === "bigint" ? expected.toString() : String(expected);
  check(name, a === e, a === e ? undefined : `expected ${e}\n          actual   ${a}`);
}

function throws(name: string, fn: () => unknown) {
  try {
    fn();
    check(name, false, "expected it to throw, it returned");
  } catch {
    check(name, true);
  }
}

/**
 * Generated by running `deriveShieldedKeysFromSignature` from
 * `app/lib/shielded/keys.ts` on 2026-08-03, at @noble/curves 1.9.7,
 * @noble/hashes 1.8.0, @scure/base 1.2.6, @zkpassport/poseidon2 0.6.2.
 */
const VECTORS = [
  {
    sig: "0x" + "11".repeat(65),
    sk: "1641326424314460259424649516660982331919157625080492310996030359160137273284",
    nk: "11785734938051342002322805656159859671754255157636385302097803582767753414151",
    mpk: "19310147387496249497389778094245593375588157221986586778614987689059022698849",
    viewPriv:
      "22707267557670354600752712589527684146791442329134425841874141351199572481509",
    viewPubHex: "028a34e71ff37b29bd0c947c138e3dd5f8979307a2bd2653a4ccd43509f4883a82",
    paymentAddress:
      "zcowl192cj0a56j0z5f430jnc6cgh8c3pyy29rmchdcypykl24f0dw09ss9z35uu0lx7efh5xfglqn3c7at7yhjvr690fx2wjve4p4p86gsw5ztfgclu",
  },
  {
    sig: "0x" + "00".repeat(64) + "1b",
    sk: "11745473355619077891793671704803375129699448223658683777891929278236448926519",
    nk: "7432910320752176565123395085368853284777574864319441189808448378701966142367",
    mpk: "20140695494613696544633620788562049945171316679651437306915780361171209356561",
    viewPriv:
      "59799296494018026127955667611839887346819864201721775492762879100015899955946",
    viewPubHex: "0253b06e743a0454082875132654bdec589cad36377b248ad1b0a66bf50217080e",
    paymentAddress:
      "zcowl19jrn4nqn6tgu2m2c6m7v8qkvwa2eky0s8ejpegshnl594wgaq5gsy5asde6r5pz5pq582yex2j77ckyu45mrw7ey3tgmpfnt75ppwzqw59fspv",
  },
  {
    sig:
      "0xa1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90" +
      "112233445566778899aabbccddeeff00112233445566778899aabbccddeeff00" +
      "1c",
    sk: "13664920662970668066045853210112092169874381819758291253124168706687564225245",
    nk: "8542090668916743623120128888293033007154887252890493503406270639833513431294",
    mpk: "2392074774367024666561395503996896316403678266887492730772431322171374738347",
    viewPriv:
      "21668967741297966332004583190081847037512324751576394161966056895383160316137",
    viewPubHex: "031e3a918fdcab0d9105421093ed379f671dd7e115a144536f8482cc9fcb8b00fa",
    paymentAddress:
      "zcowl1q4yamj9gantujdnytnzst0djqda8dt4yxs6vdh5ejupss2j6nw4sx836jx8ae2cdjyz5yyyna5me7eca6ls3tg2y2dhcfqkvnl9ckq86lfchlc",
  },
];

console.log("\nThe signed message, byte for byte");
/**
 * Not cosmetic. This string is the seed. One different byte is a different
 * wallet, so it is asserted whole rather than by length or prefix.
 */
eq(
  "matches app/lib/shielded/keys.ts",
  SHIELDED_SIGN_MESSAGE,
  "Cowl Protocol shielded account v1\n\n" +
    "This signature derives the keys to your shielded balance. " +
    "Only sign it on app.cowlprotocol.com.",
);

console.log("\nDerivation, against known answers from the dapp");
for (const [i, v] of VECTORS.entries()) {
  const k = deriveFromSignature(v.sig);
  eq(`vector ${i} · sk`, k.sk, v.sk);
  eq(`vector ${i} · nk`, k.nk, v.nk);
  eq(`vector ${i} · mpk`, k.mpk, v.mpk);
  eq(`vector ${i} · viewPriv`, k.viewPriv, v.viewPriv);
  eq(`vector ${i} · viewPubHex`, k.viewPubHex, v.viewPubHex);
  eq(`vector ${i} · paymentAddress`, k.paymentAddress, v.paymentAddress);
}

console.log("\nProperties that must hold for every derivation");
for (const [i, v] of VECTORS.entries()) {
  const k = deriveFromSignature(v.sig);

  const again = deriveFromSignature(v.sig);
  check(
    `vector ${i} · deriving twice gives the same account`,
    again.mpk === k.mpk && again.paymentAddress === k.paymentAddress,
  );

  // Anything at or above the modulus is not a field element and would be
  // reduced somewhere downstream, silently changing the owner of a note.
  check(`vector ${i} · sk, nk and mpk are in the field`, k.sk < FR && k.nk < FR && k.mpk < FR);

  // 33 bytes starting 02 or 03. An uncompressed or malformed point would be
  // encoded into the address and every payer would fail to encrypt to it.
  check(
    `vector ${i} · viewPub is a compressed point`,
    /^0[23][0-9a-f]{64}$/.test(k.viewPubHex),
  );

  const round = decodePaymentAddress(k.paymentAddress);
  check(
    `vector ${i} · address round trips`,
    round.mpk === k.mpk && round.viewPubHex === k.viewPubHex,
  );

  // The address is published. If a secret can be read back out of it, the
  // product is over. sk and viewPriv must appear nowhere in the payload.
  const payload = Buffer.from(k.paymentAddress).toString("hex");
  check(
    `vector ${i} · address carries no secret`,
    !payload.includes(k.sk.toString(16)) && !payload.includes(k.viewPriv.toString(16)),
  );

  // QR alphanumeric mode is upper case only, and bech32 forbids mixed case, so
  // a scanned address arrives shouting and still has to decode.
  check(
    `vector ${i} · upper case decodes, for QR`,
    decodePaymentAddress(k.paymentAddress.toUpperCase()).mpk === k.mpk,
  );
}

console.log("\nAddress format, pinned independently of derivation");
{
  const fixedMpk = 123456789012345678901234567890n;
  const fixedView = "02" + "ab".repeat(32);
  eq(
    "fixed inputs encode to the dapp's answer",
    encodePaymentAddress(fixedMpk, fixedView),
    "zcowl1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp3m5slakrw0swun3lptfq92at4w46h2at4w46h2at4w46h2at4w46h2at4w46h2at4w46h2atwkent9",
  );

  // Addresses were handed out in the pre-checksum form and still have to be
  // payable, so this path cannot be dropped as dead code.
  const legacy = "zcowl:0x" + "22".repeat(32) + "03" + "55".repeat(32);
  const dec = decodePaymentAddress(legacy);
  eq(
    "legacy zcowl:0x form still decodes",
    dec.mpk,
    "15438945231642159389809464667825054380435997955418741871927677867721750618658",
  );
  eq("legacy view key survives", dec.viewPubHex, "03" + "55".repeat(32));
}

console.log("\nRefusals · a mistyped address must fail, never pay someone else");
{
  const good = VECTORS[0]!.paymentAddress;

  // The checksum is the whole reason for bech32m here. A note sent to an mpk
  // nobody holds is unrecoverable by anyone, including us.
  const flipped = good.slice(0, -1) + (good.at(-1) === "u" ? "w" : "u");
  throws("one flipped character fails the checksum", () => decodePaymentAddress(flipped));

  throws("truncated address is refused", () => decodePaymentAddress(good.slice(0, 40)));
  throws("empty string is refused", () => decodePaymentAddress(""));
  throws("a plain 0x wallet address is refused", () =>
    decodePaymentAddress("0xd5F69BCf7B0B0F1cF0Ef7cF5c1CE60F4d1eb2eff"),
  );
  // Right encoding, wrong network prefix. Silently accepting it would pay an
  // address from another chain's book.
  throws("a bech32m string with another prefix is refused", () =>
    decodePaymentAddress("bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4"),
  );
  // Correct prefix and a valid checksum, but the wrong payload length, which is
  // what a truncated or padded copy looks like after a bad round trip. The
  // checksum cannot catch this one, so the explicit length check has to.
  throws("right prefix, valid checksum, wrong payload length, is refused", () =>
    decodePaymentAddress(encodePaymentAddress(1n, "02" + "ab".repeat(20))),
  );

  check("isPaymentAddress accepts a real one", isPaymentAddress(good));
  check("isPaymentAddress rejects a flipped one", !isPaymentAddress(flipped));
  check("isPaymentAddress rejects a wallet address", !isPaymentAddress("0xdeadbeef"));

  throws("a signature under 64 bytes is refused", () =>
    deriveFromSignature("0x" + "11".repeat(32)),
  );
  throws("an empty signature is refused", () => deriveFromSignature("0x"));
}

console.log(
  failures === 0
    ? "\nAll checks passed. This client derives the same account as the dapp.\n"
    : `\n${failures} check(s) failed.\n`,
);
process.exit(failures === 0 ? 0 : 1);
