/**
 * Can this client read a note the other clients wrote? Run with `npm run test:notes`.
 *
 * **The vectors below were generated by the shipped dapp**, from
 * `app/lib/shielded/crypto.ts` and `app/lib/shielded/note.ts`, and are frozen.
 * They are deliberately not regenerated from this repository, which would only
 * prove that app-v2 agrees with itself. The same rule `test:keys` follows, for
 * the same reason.
 *
 * **What breaks if this fails is not a screen.** One shielded account is meant
 * to work from the CLI, the dapp and this app, and it does because AES-256-GCM
 * is deterministic in (key, iv, plaintext) and all three pack the payload the
 * same way. A client that cannot open the others' ciphers does not throw: it
 * finds no notes, reports a balance of zero, and looks exactly like an account
 * that was robbed.
 *
 * Offline. No key of anybody's, no chain, no network.
 */
import { commitment, type Note } from "../src/features/shielded/lib/note";
import { tryDecryptNote, unpackCipher } from "../src/features/shielded/lib/note-cipher";
import { fieldToHex } from "../src/lib/field";

/** Derived from fixed phrases in the generator, so it owns nothing anywhere. */
const VIEW_PRIV = 0x5afd1834344a5da704e08cc4d57d7811461078bf546a0c6f4700741f68176e7an;
const MPK = 0xdf0525114967369065185ef8eca85da6272af1e48ff5a78807cf2f800083b804n;

const VECTORS = [
  {
    label: "usdg, six decimals",
    packed:
      "0x03ef19c1b57aafeb4ff0087bc7ab083d8938ff2a1d1431a37d76b901caa27e1bbb83bcd403ce7af97efdde3342fc3e18a252f821c2218510cefc6e9d60f91eabe5141e60be3e0d4a88505c09c388f9cbe38e8288966dfbec8b86c7eca8b95f9f069fa6adbc7be8082b436ef01410e8d2d6f2ebf263468b500ba0f360bd0a4abd6d15c02838ec58dac0e2205eac04307f4f145e75f173a13a5ece3bb05f07",
    value: 500000000n,
    token: 0xa82762eda1af5ed19b9bd544c121dbcf365526acn,
    blinding: 0x1234567890abcdefn,
    commitment: "0x151d4f017b891d5d31aa61c1b6bd68dd6b256b073b861bab880d4231fcb9b26e",
  },
  {
    label: "native coin, token id zero",
    packed:
      "0x027c6b67ae53b7ea1b1e57cc0e1b6facc811e6d2b2da4bb45485e142eb039636f65d26927a5772d127aec351892c476134e65774914c894ef91acff91f3efea61da0c7067f5264a7b64c4dd2f704d28c96457974779694a09e842ee2bb078503b6307fd2a728260bac56c2ccf4b0f4226bfd366e8b90785aca6f618b286e80ffb334aff26d3b5650f8daf30874295db20bbe42b2c6e2b5fb8ab8f78a0029",
    value: 1482000000000000000n,
    token: 0n,
    blinding: 0xfeedfacecafebeefn,
    commitment: "0x0aa2245165c6582a590ffc86c74c903b2587b47aeb6b355f9f807131806037da",
  },
  {
    /* A join-split writes two outputs whether or not there is change, so this
       is the ordinary shape of a note and not an edge case invented for a test.
       It also has to survive the scan: a zero note that failed to decrypt would
       be indistinguishable from a leaf this client cannot read. */
    label: "zero value, the change a spend leaves behind",
    packed:
      "0x03da7df448e84e5b26a9109eac9390ee816497a323110fb9fe06307a491c88fa677ccb74c3457e4be36bf8c1f90afab31a443da924661742767ecc28a56c88bb7f1ee73157541a97960d406e2cbf5412e12c2d3cab37486c6ec9593124bfe198f1fcb8f03546386fb0b7bf1ef8b1a4215f5265a3906b912d783cdbd638f0500e501413733ffc2abf3cc0517e9998bfa2306bc97babbfddd3d5776ebf82e6",
    value: 0n,
    token: 0n,
    blinding: 0x2n,
    commitment: "0x125a299f558183d73e99cec6d01669abfe37ce2c827069ea526e2064270b4dd9",
  },
] as const;

let failures = 0;
let checks = 0;

function is(label: string, actual: unknown, expected: unknown) {
  checks++;
  if (actual === expected) console.log(`  ok    ${label}`);
  else {
    failures++;
    console.log(`  FAIL  ${label}\n        expected ${String(expected)}, got ${String(actual)}`);
  }
}

console.log("\nOpening notes the dapp wrote\n");

for (const v of VECTORS) {
  const cipher = unpackCipher(v.packed);
  const opened = tryDecryptNote(cipher, VIEW_PRIV);

  if (!opened) {
    checks++;
    failures++;
    console.log(`  FAIL  ${v.label}\n        it did not decrypt at all, so this client cannot read the dapp's notes`);
    continue;
  }

  is(`${v.label} · value`, opened.value, v.value);
  is(`${v.label} · token`, opened.token, v.token);
  is(`${v.label} · blinding`, opened.blinding, v.blinding);

  /* The commitment is what makes a decrypted note *ours*. Rebuilt here with
     this client's Poseidon2 and compared to the one the dapp computed, so a
     drift in the hash shows up as a mismatch rather than as an empty balance. */
  const note: Note = { value: opened.value, token: opened.token, mpk: MPK, blinding: opened.blinding };
  is(`${v.label} · commitment rebuilds to the dapp's`, fieldToHex(commitment(note)), v.commitment);
}

console.log("\nRefusing what is not ours\n");

{
  const stranger = VIEW_PRIV ^ 1n;
  is("a different view key opens nothing", tryDecryptNote(unpackCipher(VECTORS[0].packed), stranger), null);
}

{
  /* Flip one byte inside the ciphertext body. GCM's tag is what catches it, and
     the failure has to be a null rather than a throw: one unreadable leaf in a
     replay of thousands must not end the scan. */
  const bytes = VECTORS[0].packed.slice(2).split("");
  bytes[100] = bytes[100] === "a" ? "b" : "a";
  is("a tampered ciphertext is refused, not thrown on", tryDecryptNote(unpackCipher("0x" + bytes.join("")), VIEW_PRIV), null);
}

{
  /* A cipher of the wrong length is a different failure: the pool emits a fixed
     158 bytes, so anything else means the layout assumption is wrong, and that
     is worth stopping on rather than skipping quietly. */
  checks++;
  try {
    unpackCipher(VECTORS[0].packed.slice(0, 60));
    failures++;
    console.log("  FAIL  a short cipher is refused\n        it unpacked something out of the wrong number of bytes");
  } catch {
    console.log("  ok    a short cipher is refused rather than half read");
  }
}

console.log(
  failures === 0
    ? `\nAll ${checks} note checks pass. This client reads what the dapp writes.\n`
    : `\n${failures} of ${checks} note checks FAILED.\n`,
);
process.exit(failures === 0 ? 0 : 1);
